import smtplib
import mimetypes
from email.message import EmailMessage
from pathlib import Path

from env_loader import load_env


ROOT = Path(__file__).resolve().parent


def send_email(to_email, subject, body, attachments=None):
    env = load_env(ROOT)
    mode = env.get("AGENT_MODE", "dry_run")
    address = env.get("GMAIL_ADDRESS", "")
    password = env.get("GMAIL_APP_PASSWORD", "")
    attachments = attachments or []

    if mode == "dry_run" or not address or not password:
        print("[DRY RUN] Email:")
        print(f"From: {address or '[missing Gmail address]'}")
        print(f"To: {to_email}")
        print(f"Subject: {subject}")
        print(body)
        if attachments:
            print("Attachments:", ", ".join(str(Path(item)) for item in attachments))
        return {"ok": True, "dry_run": True}

    message = EmailMessage()
    message["From"] = address
    message["To"] = to_email
    message["Subject"] = subject
    message.set_content(body)

    for attachment in attachments:
        path = Path(attachment)
        mime_type = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
        maintype, subtype = mime_type.split("/", 1)
        message.add_attachment(path.read_bytes(), maintype=maintype, subtype=subtype, filename=path.name)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=30) as smtp:
        smtp.login(address, password)
        smtp.send_message(message)

    return {"ok": True, "dry_run": False}


def verify_gmail_login():
    env = load_env(ROOT)
    address = env.get("GMAIL_ADDRESS", "")
    password = env.get("GMAIL_APP_PASSWORD", "")

    if not address:
        return {"ok": False, "error": "missing GMAIL_ADDRESS"}
    if not password:
        return {"ok": False, "error": "missing GMAIL_APP_PASSWORD"}

    with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=30) as smtp:
        smtp.login(address, password)
    return {"ok": True, "message": "Gmail login accepted. No email was sent by this check."}


if __name__ == "__main__":
    send_email(
        "recruiter@example.com",
        "Application - Demo Candidate",
        "This is a local dry-run email generated by Agent HR.",
    )
